[package]
name = "subzero-rocket"
version = "0.1.0"
edition = "2018"
autobins = false
autobenches = false

[dependencies]
bytes = "1.1.0"
rocket = "0.5.0-rc.1"
subzero = { version = "0.1.0", path = "../lib" }
http = "0.2"
lazy_static = "1.4.0"
snafu = "0.6.10"
figment = { version = "0.10.6", features = ["toml", "env"] }
hyper = { version = "0.14", features = ["full"] }
# hyper-reverse-proxy = "0.5"

[features]
default = ["all"]
all = ["postgresql", "sqlite"]
postgresql = ["subzero/postgresql"]
sqlite = ["subzero/sqlite"]

[[bin]]
name = "subzero"
path = "src/main.rs"

[dev-dependencies]
pretty_assertions = "1.0.0"
speculate = "0.1.2"
demonstrate = "0.4.5"
async_once = "0.2.1"
rand = "0.8.5"
serde_json = "1.0.68"
