/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040201
#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NULLPTR nullptr
#else
# define SWIG_NULLPTR NULL
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } } while (0)

/* SWIG Errors applicable to all language modules, values are reserved from -1 to -99 */
#define  SWIG_UnknownError    	   -1
#define  SWIG_IOError        	   -2
#define  SWIG_RuntimeError   	   -3
#define  SWIG_IndexError     	   -4
#define  SWIG_TypeError      	   -5
#define  SWIG_DivisionByZero 	   -6
#define  SWIG_OverflowError  	   -7
#define  SWIG_SyntaxError    	   -8
#define  SWIG_ValueError     	   -9
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12
#define  SWIG_NullReferenceError   -13



    #include "subzero.h"

SWIGINTERN struct sbz_HTTPRequest *new_sbz_HTTPRequest(char const *method,char const *uri,char const *body,char const **headers,int headers_count,char const **env,int env_count){
        return sbz_http_request_new_with_clone(method, uri, body, headers, headers_count, env, env_count);
    }
SWIGINTERN void delete_sbz_HTTPRequest(struct sbz_HTTPRequest *self){
        sbz_http_request_free(self);
    }
SWIGINTERN struct sbz_DbSchema *new_sbz_DbSchema(char const *db_type,char const *db_schema_json,char const *license_key){
        return sbz_db_schema_new(db_type, db_schema_json, license_key);
    }
SWIGINTERN bool sbz_DbSchema_isDemo(struct sbz_DbSchema *self){
        return sbz_db_schema_is_demo(self) > 0;
    }
SWIGINTERN void delete_sbz_DbSchema(struct sbz_DbSchema *self){
        sbz_db_schema_free(self);
    }
SWIGINTERN struct sbz_Statement *new_sbz_Statement(char const *schema_name,char const *path_prefix,char const *role,struct sbz_DbSchema const *db_schema,struct sbz_HTTPRequest const *request,char const *max_rows){
        return sbz_statement_main_new(schema_name, path_prefix, role, db_schema, request, max_rows);
    }
SWIGINTERN sbz_Statement *sbz_Statement_mainStatement(char const *schema_name,char const *path_prefix,char const *role,struct sbz_DbSchema const *db_schema,struct sbz_HTTPRequest const *request,char const *max_rows){
        return sbz_statement_main_new(schema_name, path_prefix, role, db_schema, request, max_rows);
    }
SWIGINTERN sbz_Statement *sbz_Statement_envStatement(struct sbz_DbSchema const *db_schema,struct sbz_HTTPRequest const *request){
        return sbz_statement_env_new(db_schema, request);
    }
SWIGINTERN void delete_sbz_Statement(struct sbz_Statement *self){
        sbz_statement_free(self);
    }
SWIGINTERN char *sbz_Statement_getSql(struct sbz_Statement *self){
        return (char *)sbz_statement_sql(self);
    }
SWIGINTERN char **sbz_Statement_getParams(struct sbz_Statement *self){
        int count = sbz_statement_params_count(self);
        const char *const *params = sbz_statement_params(self);
        char **result = (char **)malloc((count+1)*sizeof(char *));
        for (int i = 0; i < count; i++) {
            result[i] = strdup(params[i]);
        }
        result[count] = 0;
        return result;
    }
SWIGINTERN char **sbz_Statement_getParamsTypes(struct sbz_Statement *self){
        //return (char **)sbz_statement_params_types(self);
        int count = sbz_statement_params_count(self);
        const char *const *params = sbz_statement_params_types(self);
        char **result = (char **)malloc((count+1)*sizeof(char *));
        for (int i = 0; i < count; i++) {
            result[i] = strdup(params[i]);
        }
        result[count] = 0;
        return result;
    }
SWIGINTERN struct sbz_TwoStageStatement *new_sbz_TwoStageStatement(char const *schema_name,char const *path_prefix,char const *role,struct sbz_DbSchema const *db_schema,struct sbz_HTTPRequest const *request,char const *max_rows){
        return sbz_two_stage_statement_new(schema_name, path_prefix, role, db_schema, request, max_rows);
    }
SWIGINTERN sbz_Statement const *sbz_TwoStageStatement_mutateStatement(struct sbz_TwoStageStatement *self){
        return sbz_two_stage_statement_mutate(self);
    }
SWIGINTERN sbz_Statement const *sbz_TwoStageStatement_selectStatement(struct sbz_TwoStageStatement *self){
        return sbz_two_stage_statement_select(self);
    }
SWIGINTERN int sbz_TwoStageStatement_setIds(struct sbz_TwoStageStatement *self,char const **ids,int ids_count){
        return sbz_two_stage_statement_set_ids(self, ids, ids_count);
    }
SWIGINTERN void delete_sbz_TwoStageStatement(struct sbz_TwoStageStatement *self){
        sbz_two_stage_statement_free(self);
    }

SWIGINTERN void SWIG_JavaException(JNIEnv *jenv, int code, const char *msg) {
  SWIG_JavaExceptionCodes exception_code = SWIG_JavaUnknownError;
  switch(code) {
  case SWIG_MemoryError:
    exception_code = SWIG_JavaOutOfMemoryError;
    break;
  case SWIG_IOError:
    exception_code = SWIG_JavaIOException;
    break;
  case SWIG_SystemError:
  case SWIG_RuntimeError:
    exception_code = SWIG_JavaRuntimeException;
    break;
  case SWIG_OverflowError:
  case SWIG_IndexError:
    exception_code = SWIG_JavaIndexOutOfBoundsException;
    break;
  case SWIG_DivisionByZero:
    exception_code = SWIG_JavaArithmeticException;
    break;
  case SWIG_SyntaxError:
  case SWIG_ValueError:
  case SWIG_TypeError:
    exception_code = SWIG_JavaIllegalArgumentException;
    break;
  case SWIG_UnknownError:
  default:
    exception_code = SWIG_JavaUnknownError;
    break;
  }
  SWIG_JavaThrowException(jenv, exception_code, msg);
}


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_com_subzero_swig_SubzeroJNI_new_1sbz_1HTTPRequest(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2, jstring jarg3, jobjectArray jarg4, jint jarg5, jobjectArray jarg6, jint jarg7) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char **arg4 = (char **) 0 ;
  int arg5 ;
  char **arg6 = (char **) 0 ;
  int arg7 ;
  jint size4 ;
  jint size6 ;
  struct sbz_HTTPRequest *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  {
    int i = 0;
    size4 = (*jenv)->GetArrayLength(jenv, jarg4);
    arg4 = (char **) malloc((size4+1)*sizeof(char *));
    /* make a copy of each string */
    for (i = 0; i<size4; i++) {
      jstring j_string = (jstring)(*jenv)->GetObjectArrayElement(jenv, jarg4, i);
      const char * c_string = (*jenv)->GetStringUTFChars(jenv, j_string, 0);
      arg4[i] = malloc((strlen(c_string)+1)*sizeof(char));
      strcpy(arg4[i], c_string);
      (*jenv)->ReleaseStringUTFChars(jenv, j_string, c_string);
      (*jenv)->DeleteLocalRef(jenv, j_string);
    }
    arg4[i] = 0;
  }
  arg5 = (int)jarg5; 
  {
    int i = 0;
    size6 = (*jenv)->GetArrayLength(jenv, jarg6);
    arg6 = (char **) malloc((size6+1)*sizeof(char *));
    /* make a copy of each string */
    for (i = 0; i<size6; i++) {
      jstring j_string = (jstring)(*jenv)->GetObjectArrayElement(jenv, jarg6, i);
      const char * c_string = (*jenv)->GetStringUTFChars(jenv, j_string, 0);
      arg6[i] = malloc((strlen(c_string)+1)*sizeof(char));
      strcpy(arg6[i], c_string);
      (*jenv)->ReleaseStringUTFChars(jenv, j_string, c_string);
      (*jenv)->DeleteLocalRef(jenv, j_string);
    }
    arg6[i] = 0;
  }
  arg7 = (int)jarg7; 
  {
    result = (struct sbz_HTTPRequest *)new_sbz_HTTPRequest((char const *)arg1,(char const *)arg2,(char const *)arg3,(char const **)arg4,arg5,(char const **)arg6,arg7);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  *(struct sbz_HTTPRequest **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  {
    int i;
    for (i=0; i<size4-1; i++)
    free(arg4[i]);
    free(arg4);
  }
  {
    int i;
    for (i=0; i<size6-1; i++)
    free(arg6[i]);
    free(arg6);
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_subzero_swig_SubzeroJNI_delete_1sbz_1HTTPRequest(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct sbz_HTTPRequest *arg1 = (struct sbz_HTTPRequest *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct sbz_HTTPRequest **)&jarg1; 
  {
    delete_sbz_HTTPRequest(arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return ;
    }
  }
}


SWIGEXPORT jlong JNICALL Java_com_subzero_swig_SubzeroJNI_new_1sbz_1DbSchema(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2, jstring jarg3) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  struct sbz_DbSchema *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  {
    result = (struct sbz_DbSchema *)new_sbz_DbSchema((char const *)arg1,(char const *)arg2,(char const *)arg3);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  *(struct sbz_DbSchema **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1DbSchema_1isDemo(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  struct sbz_DbSchema *arg1 = (struct sbz_DbSchema *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct sbz_DbSchema **)&jarg1; 
  {
    result = (bool)sbz_DbSchema_isDemo(arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_subzero_swig_SubzeroJNI_delete_1sbz_1DbSchema(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct sbz_DbSchema *arg1 = (struct sbz_DbSchema *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct sbz_DbSchema **)&jarg1; 
  {
    delete_sbz_DbSchema(arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return ;
    }
  }
}


SWIGEXPORT jlong JNICALL Java_com_subzero_swig_SubzeroJNI_new_1sbz_1Statement(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2, jstring jarg3, jlong jarg4, jobject jarg4_, jlong jarg5, jobject jarg5_, jstring jarg6) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  struct sbz_DbSchema *arg4 = (struct sbz_DbSchema *) 0 ;
  struct sbz_HTTPRequest *arg5 = (struct sbz_HTTPRequest *) 0 ;
  char *arg6 = (char *) 0 ;
  struct sbz_Statement *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg4_;
  (void)jarg5_;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = *(struct sbz_DbSchema **)&jarg4; 
  arg5 = *(struct sbz_HTTPRequest **)&jarg5; 
  arg6 = 0;
  if (jarg6) {
    arg6 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg6, 0);
    if (!arg6) return 0;
  }
  {
    result = (struct sbz_Statement *)new_sbz_Statement((char const *)arg1,(char const *)arg2,(char const *)arg3,(struct sbz_DbSchema const *)arg4,(struct sbz_HTTPRequest const *)arg5,(char const *)arg6);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  *(struct sbz_Statement **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  if (arg6) (*jenv)->ReleaseStringUTFChars(jenv, jarg6, (const char *)arg6);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1Statement_1mainStatement(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2, jstring jarg3, jlong jarg4, jobject jarg4_, jlong jarg5, jobject jarg5_, jstring jarg6) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  struct sbz_DbSchema *arg4 = (struct sbz_DbSchema *) 0 ;
  struct sbz_HTTPRequest *arg5 = (struct sbz_HTTPRequest *) 0 ;
  char *arg6 = (char *) 0 ;
  sbz_Statement *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg4_;
  (void)jarg5_;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = *(struct sbz_DbSchema **)&jarg4; 
  arg5 = *(struct sbz_HTTPRequest **)&jarg5; 
  arg6 = 0;
  if (jarg6) {
    arg6 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg6, 0);
    if (!arg6) return 0;
  }
  {
    result = (sbz_Statement *)sbz_Statement_mainStatement((char const *)arg1,(char const *)arg2,(char const *)arg3,(struct sbz_DbSchema const *)arg4,(struct sbz_HTTPRequest const *)arg5,(char const *)arg6);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  *(sbz_Statement **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  if (arg6) (*jenv)->ReleaseStringUTFChars(jenv, jarg6, (const char *)arg6);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1Statement_1envStatement(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jlong jresult = 0 ;
  struct sbz_DbSchema *arg1 = (struct sbz_DbSchema *) 0 ;
  struct sbz_HTTPRequest *arg2 = (struct sbz_HTTPRequest *) 0 ;
  sbz_Statement *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct sbz_DbSchema **)&jarg1; 
  arg2 = *(struct sbz_HTTPRequest **)&jarg2; 
  {
    result = (sbz_Statement *)sbz_Statement_envStatement((struct sbz_DbSchema const *)arg1,(struct sbz_HTTPRequest const *)arg2);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  *(sbz_Statement **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_subzero_swig_SubzeroJNI_delete_1sbz_1Statement(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct sbz_Statement *arg1 = (struct sbz_Statement *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct sbz_Statement **)&jarg1; 
  {
    delete_sbz_Statement(arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return ;
    }
  }
}


SWIGEXPORT jstring JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1Statement_1getSql(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct sbz_Statement *arg1 = (struct sbz_Statement *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct sbz_Statement **)&jarg1; 
  {
    result = (char *)sbz_Statement_getSql(arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jobjectArray JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1Statement_1getParams(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobjectArray jresult = 0 ;
  struct sbz_Statement *arg1 = (struct sbz_Statement *) 0 ;
  char **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct sbz_Statement **)&jarg1; 
  {
    result = (char **)sbz_Statement_getParams(arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  {
    int i;
    int len=0;
    jstring temp_string;
    const jclass clazz = (*jenv)->FindClass(jenv, "java/lang/String");
    
    if (result == NULL) {
      len = 0;
    }
    else {
      while (result[len]) len++;
    }
    jresult = (*jenv)->NewObjectArray(jenv, len, clazz, NULL);
    /* exception checking omitted */
    
    for (i=0; i<len; i++) {
      temp_string = (*jenv)->NewStringUTF(jenv, *result++);
      (*jenv)->SetObjectArrayElement(jenv, jresult, i, temp_string);
      (*jenv)->DeleteLocalRef(jenv, temp_string);
    }
  }
  return jresult;
}


SWIGEXPORT jobjectArray JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1Statement_1getParamsTypes(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobjectArray jresult = 0 ;
  struct sbz_Statement *arg1 = (struct sbz_Statement *) 0 ;
  char **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct sbz_Statement **)&jarg1; 
  {
    result = (char **)sbz_Statement_getParamsTypes(arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  {
    int i;
    int len=0;
    jstring temp_string;
    const jclass clazz = (*jenv)->FindClass(jenv, "java/lang/String");
    
    if (result == NULL) {
      len = 0;
    }
    else {
      while (result[len]) len++;
    }
    jresult = (*jenv)->NewObjectArray(jenv, len, clazz, NULL);
    /* exception checking omitted */
    
    for (i=0; i<len; i++) {
      temp_string = (*jenv)->NewStringUTF(jenv, *result++);
      (*jenv)->SetObjectArrayElement(jenv, jresult, i, temp_string);
      (*jenv)->DeleteLocalRef(jenv, temp_string);
    }
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_subzero_swig_SubzeroJNI_new_1sbz_1TwoStageStatement(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2, jstring jarg3, jlong jarg4, jobject jarg4_, jlong jarg5, jobject jarg5_, jstring jarg6) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  struct sbz_DbSchema *arg4 = (struct sbz_DbSchema *) 0 ;
  struct sbz_HTTPRequest *arg5 = (struct sbz_HTTPRequest *) 0 ;
  char *arg6 = (char *) 0 ;
  struct sbz_TwoStageStatement *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg4_;
  (void)jarg5_;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = *(struct sbz_DbSchema **)&jarg4; 
  arg5 = *(struct sbz_HTTPRequest **)&jarg5; 
  arg6 = 0;
  if (jarg6) {
    arg6 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg6, 0);
    if (!arg6) return 0;
  }
  {
    result = (struct sbz_TwoStageStatement *)new_sbz_TwoStageStatement((char const *)arg1,(char const *)arg2,(char const *)arg3,(struct sbz_DbSchema const *)arg4,(struct sbz_HTTPRequest const *)arg5,(char const *)arg6);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  *(struct sbz_TwoStageStatement **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  if (arg6) (*jenv)->ReleaseStringUTFChars(jenv, jarg6, (const char *)arg6);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1TwoStageStatement_1mutateStatement(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct sbz_TwoStageStatement *arg1 = (struct sbz_TwoStageStatement *) 0 ;
  sbz_Statement *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct sbz_TwoStageStatement **)&jarg1; 
  {
    result = (sbz_Statement *)sbz_TwoStageStatement_mutateStatement(arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  *(sbz_Statement **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1TwoStageStatement_1selectStatement(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct sbz_TwoStageStatement *arg1 = (struct sbz_TwoStageStatement *) 0 ;
  sbz_Statement *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct sbz_TwoStageStatement **)&jarg1; 
  {
    result = (sbz_Statement *)sbz_TwoStageStatement_selectStatement(arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  *(sbz_Statement **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1TwoStageStatement_1setIds(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2, jint jarg3) {
  jint jresult = 0 ;
  struct sbz_TwoStageStatement *arg1 = (struct sbz_TwoStageStatement *) 0 ;
  char **arg2 = (char **) 0 ;
  int arg3 ;
  jint size2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct sbz_TwoStageStatement **)&jarg1; 
  {
    int i = 0;
    size2 = (*jenv)->GetArrayLength(jenv, jarg2);
    arg2 = (char **) malloc((size2+1)*sizeof(char *));
    /* make a copy of each string */
    for (i = 0; i<size2; i++) {
      jstring j_string = (jstring)(*jenv)->GetObjectArrayElement(jenv, jarg2, i);
      const char * c_string = (*jenv)->GetStringUTFChars(jenv, j_string, 0);
      arg2[i] = malloc((strlen(c_string)+1)*sizeof(char));
      strcpy(arg2[i], c_string);
      (*jenv)->ReleaseStringUTFChars(jenv, j_string, c_string);
      (*jenv)->DeleteLocalRef(jenv, j_string);
    }
    arg2[i] = 0;
  }
  arg3 = (int)jarg3; 
  {
    result = (int)sbz_TwoStageStatement_setIds(arg1,(char const **)arg2,arg3);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  jresult = (jint)result; 
  {
    int i;
    for (i=0; i<size2-1; i++)
    free(arg2[i]);
    free(arg2);
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_subzero_swig_SubzeroJNI_delete_1sbz_1TwoStageStatement(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct sbz_TwoStageStatement *arg1 = (struct sbz_TwoStageStatement *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct sbz_TwoStageStatement **)&jarg1; 
  {
    delete_sbz_TwoStageStatement(arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return ;
    }
  }
}


SWIGEXPORT jlong JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1http_1request_1new_1with_1clone(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2, jstring jarg3, jobjectArray jarg4, jint jarg5, jobjectArray jarg6, jint jarg7) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char **arg4 = (char **) 0 ;
  int arg5 ;
  char **arg6 = (char **) 0 ;
  int arg7 ;
  jint size4 ;
  jint size6 ;
  struct sbz_HTTPRequest *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  {
    int i = 0;
    size4 = (*jenv)->GetArrayLength(jenv, jarg4);
    arg4 = (char **) malloc((size4+1)*sizeof(char *));
    /* make a copy of each string */
    for (i = 0; i<size4; i++) {
      jstring j_string = (jstring)(*jenv)->GetObjectArrayElement(jenv, jarg4, i);
      const char * c_string = (*jenv)->GetStringUTFChars(jenv, j_string, 0);
      arg4[i] = malloc((strlen(c_string)+1)*sizeof(char));
      strcpy(arg4[i], c_string);
      (*jenv)->ReleaseStringUTFChars(jenv, j_string, c_string);
      (*jenv)->DeleteLocalRef(jenv, j_string);
    }
    arg4[i] = 0;
  }
  arg5 = (int)jarg5; 
  {
    int i = 0;
    size6 = (*jenv)->GetArrayLength(jenv, jarg6);
    arg6 = (char **) malloc((size6+1)*sizeof(char *));
    /* make a copy of each string */
    for (i = 0; i<size6; i++) {
      jstring j_string = (jstring)(*jenv)->GetObjectArrayElement(jenv, jarg6, i);
      const char * c_string = (*jenv)->GetStringUTFChars(jenv, j_string, 0);
      arg6[i] = malloc((strlen(c_string)+1)*sizeof(char));
      strcpy(arg6[i], c_string);
      (*jenv)->ReleaseStringUTFChars(jenv, j_string, c_string);
      (*jenv)->DeleteLocalRef(jenv, j_string);
    }
    arg6[i] = 0;
  }
  arg7 = (int)jarg7; 
  {
    result = (struct sbz_HTTPRequest *)sbz_http_request_new_with_clone((char const *)arg1,(char const *)arg2,(char const *)arg3,(char const *const *)arg4,arg5,(char const *const *)arg6,arg7);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  *(struct sbz_HTTPRequest **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  {
    int i;
    for (i=0; i<size4-1; i++)
    free(arg4[i]);
    free(arg4);
  }
  {
    int i;
    for (i=0; i<size6-1; i++)
    free(arg6[i]);
    free(arg6);
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1http_1request_1new(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2, jstring jarg3, jobjectArray jarg4, jint jarg5, jobjectArray jarg6, jint jarg7) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char **arg4 = (char **) 0 ;
  int arg5 ;
  char **arg6 = (char **) 0 ;
  int arg7 ;
  jint size4 ;
  jint size6 ;
  struct sbz_HTTPRequest *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  {
    int i = 0;
    size4 = (*jenv)->GetArrayLength(jenv, jarg4);
    arg4 = (char **) malloc((size4+1)*sizeof(char *));
    /* make a copy of each string */
    for (i = 0; i<size4; i++) {
      jstring j_string = (jstring)(*jenv)->GetObjectArrayElement(jenv, jarg4, i);
      const char * c_string = (*jenv)->GetStringUTFChars(jenv, j_string, 0);
      arg4[i] = malloc((strlen(c_string)+1)*sizeof(char));
      strcpy(arg4[i], c_string);
      (*jenv)->ReleaseStringUTFChars(jenv, j_string, c_string);
      (*jenv)->DeleteLocalRef(jenv, j_string);
    }
    arg4[i] = 0;
  }
  arg5 = (int)jarg5; 
  {
    int i = 0;
    size6 = (*jenv)->GetArrayLength(jenv, jarg6);
    arg6 = (char **) malloc((size6+1)*sizeof(char *));
    /* make a copy of each string */
    for (i = 0; i<size6; i++) {
      jstring j_string = (jstring)(*jenv)->GetObjectArrayElement(jenv, jarg6, i);
      const char * c_string = (*jenv)->GetStringUTFChars(jenv, j_string, 0);
      arg6[i] = malloc((strlen(c_string)+1)*sizeof(char));
      strcpy(arg6[i], c_string);
      (*jenv)->ReleaseStringUTFChars(jenv, j_string, c_string);
      (*jenv)->DeleteLocalRef(jenv, j_string);
    }
    arg6[i] = 0;
  }
  arg7 = (int)jarg7; 
  {
    result = (struct sbz_HTTPRequest *)sbz_http_request_new((char const *)arg1,(char const *)arg2,(char const *)arg3,(char const *const *)arg4,arg5,(char const *const *)arg6,arg7);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  *(struct sbz_HTTPRequest **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  {
    int i;
    for (i=0; i<size4-1; i++)
    free(arg4[i]);
    free(arg4);
  }
  {
    int i;
    for (i=0; i<size6-1; i++)
    free(arg6[i]);
    free(arg6);
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1http_1request_1free(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  struct sbz_HTTPRequest *arg1 = (struct sbz_HTTPRequest *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct sbz_HTTPRequest **)&jarg1; 
  {
    sbz_http_request_free(arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return ;
    }
  }
}


SWIGEXPORT jlong JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1two_1stage_1statement_1new(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2, jstring jarg3, jlong jarg4, jobject jarg4_, jlong jarg5, jobject jarg5_, jstring jarg6) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  struct sbz_DbSchema *arg4 = (struct sbz_DbSchema *) 0 ;
  struct sbz_HTTPRequest *arg5 = (struct sbz_HTTPRequest *) 0 ;
  char *arg6 = (char *) 0 ;
  struct sbz_TwoStageStatement *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg4_;
  (void)jarg5_;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = *(struct sbz_DbSchema **)&jarg4; 
  arg5 = *(struct sbz_HTTPRequest **)&jarg5; 
  arg6 = 0;
  if (jarg6) {
    arg6 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg6, 0);
    if (!arg6) return 0;
  }
  {
    result = (struct sbz_TwoStageStatement *)sbz_two_stage_statement_new((char const *)arg1,(char const *)arg2,(char const *)arg3,(struct sbz_DbSchema const *)arg4,(struct sbz_HTTPRequest const *)arg5,(char const *)arg6);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  *(struct sbz_TwoStageStatement **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  if (arg6) (*jenv)->ReleaseStringUTFChars(jenv, jarg6, (const char *)arg6);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1two_1stage_1statement_1mutate(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct sbz_TwoStageStatement *arg1 = (struct sbz_TwoStageStatement *) 0 ;
  struct sbz_Statement *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct sbz_TwoStageStatement **)&jarg1; 
  {
    result = (struct sbz_Statement *)sbz_two_stage_statement_mutate((struct sbz_TwoStageStatement const *)arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  *(struct sbz_Statement **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1two_1stage_1statement_1select(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct sbz_TwoStageStatement *arg1 = (struct sbz_TwoStageStatement *) 0 ;
  struct sbz_Statement *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct sbz_TwoStageStatement **)&jarg1; 
  {
    result = (struct sbz_Statement *)sbz_two_stage_statement_select((struct sbz_TwoStageStatement const *)arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  *(struct sbz_Statement **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1two_1stage_1statement_1set_1ids(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2, jint jarg3) {
  jint jresult = 0 ;
  struct sbz_TwoStageStatement *arg1 = (struct sbz_TwoStageStatement *) 0 ;
  char **arg2 = (char **) 0 ;
  int arg3 ;
  jint size2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct sbz_TwoStageStatement **)&jarg1; 
  {
    int i = 0;
    size2 = (*jenv)->GetArrayLength(jenv, jarg2);
    arg2 = (char **) malloc((size2+1)*sizeof(char *));
    /* make a copy of each string */
    for (i = 0; i<size2; i++) {
      jstring j_string = (jstring)(*jenv)->GetObjectArrayElement(jenv, jarg2, i);
      const char * c_string = (*jenv)->GetStringUTFChars(jenv, j_string, 0);
      arg2[i] = malloc((strlen(c_string)+1)*sizeof(char));
      strcpy(arg2[i], c_string);
      (*jenv)->ReleaseStringUTFChars(jenv, j_string, c_string);
      (*jenv)->DeleteLocalRef(jenv, j_string);
    }
    arg2[i] = 0;
  }
  arg3 = (int)jarg3; 
  {
    result = (int)sbz_two_stage_statement_set_ids(arg1,(char const *const *)arg2,arg3);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  jresult = (jint)result; 
  {
    int i;
    for (i=0; i<size2-1; i++)
    free(arg2[i]);
    free(arg2);
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1two_1stage_1statement_1free(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  struct sbz_TwoStageStatement *arg1 = (struct sbz_TwoStageStatement *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct sbz_TwoStageStatement **)&jarg1; 
  {
    sbz_two_stage_statement_free(arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return ;
    }
  }
}


SWIGEXPORT jlong JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1statement_1main_1new(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2, jstring jarg3, jlong jarg4, jobject jarg4_, jlong jarg5, jobject jarg5_, jstring jarg6) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  struct sbz_DbSchema *arg4 = (struct sbz_DbSchema *) 0 ;
  struct sbz_HTTPRequest *arg5 = (struct sbz_HTTPRequest *) 0 ;
  char *arg6 = (char *) 0 ;
  struct sbz_Statement *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg4_;
  (void)jarg5_;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = *(struct sbz_DbSchema **)&jarg4; 
  arg5 = *(struct sbz_HTTPRequest **)&jarg5; 
  arg6 = 0;
  if (jarg6) {
    arg6 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg6, 0);
    if (!arg6) return 0;
  }
  {
    result = (struct sbz_Statement *)sbz_statement_main_new((char const *)arg1,(char const *)arg2,(char const *)arg3,(struct sbz_DbSchema const *)arg4,(struct sbz_HTTPRequest const *)arg5,(char const *)arg6);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  *(struct sbz_Statement **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  if (arg6) (*jenv)->ReleaseStringUTFChars(jenv, jarg6, (const char *)arg6);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1statement_1env_1new(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jlong jresult = 0 ;
  struct sbz_DbSchema *arg1 = (struct sbz_DbSchema *) 0 ;
  struct sbz_HTTPRequest *arg2 = (struct sbz_HTTPRequest *) 0 ;
  struct sbz_Statement *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct sbz_DbSchema **)&jarg1; 
  arg2 = *(struct sbz_HTTPRequest **)&jarg2; 
  {
    result = (struct sbz_Statement *)sbz_statement_env_new((struct sbz_DbSchema const *)arg1,(struct sbz_HTTPRequest const *)arg2);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  *(struct sbz_Statement **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1statement_1sql(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct sbz_Statement *arg1 = (struct sbz_Statement *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct sbz_Statement **)&jarg1; 
  {
    result = (char *)sbz_statement_sql((struct sbz_Statement const *)arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jobjectArray JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1statement_1params(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobjectArray jresult = 0 ;
  struct sbz_Statement *arg1 = (struct sbz_Statement *) 0 ;
  char **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct sbz_Statement **)&jarg1; 
  {
    result = (char **)sbz_statement_params((struct sbz_Statement const *)arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  {
    int i;
    int len=0;
    jstring temp_string;
    const jclass clazz = (*jenv)->FindClass(jenv, "java/lang/String");
    
    if (result == NULL) {
      len = 0;
    }
    else {
      while (result[len]) len++;
    }
    jresult = (*jenv)->NewObjectArray(jenv, len, clazz, NULL);
    /* exception checking omitted */
    
    for (i=0; i<len; i++) {
      temp_string = (*jenv)->NewStringUTF(jenv, *result++);
      (*jenv)->SetObjectArrayElement(jenv, jresult, i, temp_string);
      (*jenv)->DeleteLocalRef(jenv, temp_string);
    }
  }
  return jresult;
}


SWIGEXPORT jobjectArray JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1statement_1params_1types(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobjectArray jresult = 0 ;
  struct sbz_Statement *arg1 = (struct sbz_Statement *) 0 ;
  char **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct sbz_Statement **)&jarg1; 
  {
    result = (char **)sbz_statement_params_types((struct sbz_Statement const *)arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  {
    int i;
    int len=0;
    jstring temp_string;
    const jclass clazz = (*jenv)->FindClass(jenv, "java/lang/String");
    
    if (result == NULL) {
      len = 0;
    }
    else {
      while (result[len]) len++;
    }
    jresult = (*jenv)->NewObjectArray(jenv, len, clazz, NULL);
    /* exception checking omitted */
    
    for (i=0; i<len; i++) {
      temp_string = (*jenv)->NewStringUTF(jenv, *result++);
      (*jenv)->SetObjectArrayElement(jenv, jresult, i, temp_string);
      (*jenv)->DeleteLocalRef(jenv, temp_string);
    }
  }
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1statement_1params_1count(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct sbz_Statement *arg1 = (struct sbz_Statement *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct sbz_Statement **)&jarg1; 
  {
    result = (int)sbz_statement_params_count((struct sbz_Statement const *)arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1statement_1free(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  struct sbz_Statement *arg1 = (struct sbz_Statement *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct sbz_Statement **)&jarg1; 
  {
    sbz_statement_free(arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return ;
    }
  }
}


SWIGEXPORT void JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1db_1schema_1free(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  struct sbz_DbSchema *arg1 = (struct sbz_DbSchema *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct sbz_DbSchema **)&jarg1; 
  {
    sbz_db_schema_free(arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return ;
    }
  }
}


SWIGEXPORT jlong JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1db_1schema_1new(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2, jstring jarg3) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  struct sbz_DbSchema *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  {
    result = (struct sbz_DbSchema *)sbz_db_schema_new((char const *)arg1,(char const *)arg2,(char const *)arg3);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  *(struct sbz_DbSchema **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1db_1schema_1is_1demo(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct sbz_DbSchema *arg1 = (struct sbz_DbSchema *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct sbz_DbSchema **)&jarg1; 
  {
    result = (int)sbz_db_schema_is_demo((struct sbz_DbSchema const *)arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1introspection_1query(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2, jstring jarg3, jstring jarg4) {
  jstring jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return 0;
  }
  {
    result = (char *)sbz_introspection_query((char const *)arg1,(char const *)arg2,(char const *)arg3,(char const *)arg4);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1introspection_1query_1free(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  {
    sbz_introspection_query_free(arg1);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return ;
    }
  }
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT jint JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1last_1error_1message(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2) {
  jint jresult = 0 ;
  char *arg1 = (char *) 0 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (int)jarg2; 
  {
    result = (int)sbz_last_error_message(arg1,arg2);
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1clear_1last_1error(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  {
    sbz_clear_last_error();
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return ;
    }
  }
}


SWIGEXPORT jint JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1last_1error_1length(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  {
    result = (int)sbz_last_error_length();
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_subzero_swig_SubzeroJNI_sbz_1last_1error_1http_1status(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  {
    result = (int)sbz_last_error_http_status();
    const int err_len = sbz_last_error_length();
    if (err_len > 0) {
      // Check if there's an error
      char* err_msg = (char*)malloc(err_len);
      sbz_last_error_message(err_msg, err_len);
      
      jclass exceptionClass = (*jenv)->FindClass(jenv, "com/subzero/SubzeroException");
      if (exceptionClass != NULL) {
        int httpStatus = sbz_last_error_http_status();
        jmethodID constructor = (*jenv)->GetMethodID(jenv, exceptionClass, "<init>", "(Ljava/lang/String;I)V");
        jobject exception = (*jenv)->NewObject(jenv, exceptionClass, constructor, (*jenv)->NewStringUTF(jenv, err_msg), httpStatus);
        (*jenv)->Throw(jenv, exception);
      } else {
        (*jenv)->ThrowNew(jenv, (*jenv)->FindClass(jenv, "java/lang/RuntimeException"), err_msg);
      }
      
      sbz_clear_last_error();
      free(err_msg);
      return 0;
    }
  }
  jresult = (jint)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

