cargo-features = ["strip"]

[package]
name = "subzero"
version = "0.1.0"
edition = "2018"

[dependencies]
# env_logger = "0.9.0"
# url = "2.2.2"
# simple-error = "0.2.3"
http = "0.2"
rocket = "0.5.0-rc.1"
combine = "4.6.1"
lazy_static = "1.4.0"
serde = "1.0.130"
serde_json = "1.0.68"
csv = "1.1.6"
snafu = "0.6.10"
postgres-types = "0.2.2"
tokio-postgres = "0.7.4"
tokio = "1.6.1"
bytes = "1.1.0"
futures = "0.3.17"
deadpool-postgres = "0.10.0"
figment = { version = "0.10.6", features = ["toml", "env"] }
jsonwebtoken = "7.2.0"
jsonpath_lib = "0.3.0"
dashmap = "5.0.0"

[patch.crates-io]
tokio-postgres = { git = "https://github.com/subzerocloud/rust-postgres" }
postgres-types = { git = "https://github.com/subzerocloud/rust-postgres" }


[dev-dependencies]
pretty_assertions = "1.0.0"
dyn_partial_eq = "0.1.2"
criterion = "0.3"
speculate = "0.1.2"
demonstrate = "0.4.5"
regex = "1.4.6"
async_once = "0.2.1"

[[bench]]
name = "my_benchmark"
harness = false

[profile.release]
strip = true  # Automatically strip symbols from the binary.
lto = true
codegen-units = 1
panic = "abort"

# [target.x86_64-unknown-linux-gnu]
# rustflags = [
#     "-C", "link-arg=-fuse-ld=lld",
# ]