[workspace]
members = [
    "lib",
    "bin",
]

[patch.crates-io]
tokio-postgres = { git = "https://github.com/subzerocloud/rust-postgres" }
postgres-types = { git = "https://github.com/subzerocloud/rust-postgres" }
postgres-openssl = { git = "https://github.com/subzerocloud/rust-postgres" }
postgres-protocol = { git = "https://github.com/subzerocloud/rust-postgres" }