# [dependencies.rocket_sync_db_pools]
# version = "0.1.0-rc.1"
# default-features = false
# features = ["postgres_pool"]

# [global.databases.pg]
# url = "postgres://root:root@localhost/app"
# pool_size = 20

[default]
db_uri = "postgres://root:root@localhost/app"
db_schemas = ["public"]
db_schema_structure = { sql_file = "structure_query.sql" }