name: "Rustup"
description: "Use rustup to select a default toolchain and ensure it is up to date"
inputs:
  version:
    description: "The default toolchain version"
    required: false
    default: "nightly"
runs:
  using: "composite"
  steps:
    - name: Update Rust
      shell: bash
      run: |
          rustup update --no-self-update ${{ inputs.version }}
          rustup default ${{ inputs.version }}
          rustup component add rustfmt
          rustup target add wasm32-unknown-unknown
          cargo install -f wasm-bindgen-cli
    - name: Install wasm-pack
      shell: bash
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
