name: "Rustup"
description: "Use rustup to select a default toolchain and ensure it is up to date"
inputs:
  version:
    description: "The default toolchain version"
    required: false
    default: "nightly"
runs:
  using: "composite"
  steps:
    - name: Update Rust
      shell: bash
      run: |
          rustup update --no-self-update ${{ inputs.version }}
          rustup default ${{ inputs.version }}
          rustup component add rustfmt
