/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cloud.subzero.swig;

public class sbz_DbSchema {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sbz_DbSchema(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sbz_DbSchema obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(sbz_DbSchema obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SubzeroJNI.delete_sbz_DbSchema(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public sbz_DbSchema(String db_type, String db_schema_json, String license_key) {
    this(SubzeroJNI.new_sbz_DbSchema(db_type, db_schema_json, license_key), true);
  }

  public boolean isDemo() {
    return SubzeroJNI.sbz_DbSchema_isDemo(swigCPtr, this);
  }

}
