name: "Cargo cache"
description: "cache directories created by cargo"

runs:
    using: "composite"
    steps:
        - name: Install sccache
          shell: bash
          env:
              LINK: https://github.com/mozilla/sccache/releases/download
              SCCACHE_VERSION: v0.3.0
          run: |
              SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
              mkdir -p $HOME/.local/bin
              curl -L "$LINK/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
              mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
              chmod +x  $HOME/.local/bin/sccache
              echo "$HOME/.local/bin" >> $GITHUB_PATH
              # echo "SCCACHE_DIR=$GITHUB_WORKSPACE/.sccache" >> $GITHUB_ENV
        - uses: actions/cache@v3
          if: ${{ !env.ACT }}
          with:
            path: |
                ~/.cargo/bin/
                ~/.cargo/registry/index/
                ~/.cargo/registry/cache/
                ~/.cargo/git/db/
                target/
            key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            restore-keys: ${{ runner.os }}-${{ runner.arch }}-cargo-
        # - name: Save sccache
        #   if: ${{ !env.ACT }}
        #   uses: actions/cache@v2
        #   continue-on-error: false
        #   with:
        #       path: ${{ env.SCCACHE_DIR }}
        #       key: ${{ runner.os }}-${{ runner.arch }}-sccache-${{ hashFiles('**/Cargo.lock') }}
        #       restore-keys: |
        #           ${{ runner.os }}-${{ runner.arch }}-sccache-
        - name: Start sccache server
          shell: bash
          run: sccache --start-server || true
