[default]
db_uri = "postgres://app_user:password@localhost:5432/app_db"
# static_files_dir = "demo/static_files"
db_anon_role = "app_user"
url_prefix = "/"
db_type = "postgresql"
db_schemas = ["public"]
db_schema_structure = {sql_file="../introspection/postgresql_introspection_query.sql"}
# db_max_rows = 
# db_use_legacy_gucs = false
# db_pool = 10
# db_tx_rollback = false
# db_pre_request = "schema.function"
# jwt_secret = "reallysafe"
# jwt_aud = ""
# role_claim_key = ".role"
# disable_internal_permissions = true
# log_level = "debug"