/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.subzero.swig;

public class sbz_Statement {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sbz_Statement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sbz_Statement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(sbz_Statement obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SubzeroJNI.delete_sbz_Statement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public sbz_Statement(String schema_name, String path_prefix, sbz_DbSchema db_schema, sbz_HTTPRequest request, String max_rows) {
    this(SubzeroJNI.new_sbz_Statement(schema_name, path_prefix, sbz_DbSchema.getCPtr(db_schema), db_schema, sbz_HTTPRequest.getCPtr(request), request, max_rows), true);
  }

  public static sbz_Statement mainStatement(String schema_name, String path_prefix, sbz_DbSchema db_schema, sbz_HTTPRequest request, String max_rows) {
    long cPtr = SubzeroJNI.sbz_Statement_mainStatement(schema_name, path_prefix, sbz_DbSchema.getCPtr(db_schema), db_schema, sbz_HTTPRequest.getCPtr(request), request, max_rows);
    return (cPtr == 0) ? null : new sbz_Statement(cPtr, false);
  }

  public static sbz_Statement envStatement(sbz_DbSchema db_schema, sbz_HTTPRequest request) {
    long cPtr = SubzeroJNI.sbz_Statement_envStatement(sbz_DbSchema.getCPtr(db_schema), db_schema, sbz_HTTPRequest.getCPtr(request), request);
    return (cPtr == 0) ? null : new sbz_Statement(cPtr, false);
  }

  public String getSql() {
    return SubzeroJNI.sbz_Statement_getSql(swigCPtr, this);
  }

  public String[] getParams() {
    return SubzeroJNI.sbz_Statement_getParams(swigCPtr, this);
}

  public String[] getParamsTypes() {
    return SubzeroJNI.sbz_Statement_getParamsTypes(swigCPtr, this);
}

}
