/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.subzero.swig;

public class sbz_TwoStageStatement {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sbz_TwoStageStatement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sbz_TwoStageStatement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(sbz_TwoStageStatement obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SubzeroJNI.delete_sbz_TwoStageStatement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public sbz_TwoStageStatement(String schema_name, String path_prefix, String role, sbz_DbSchema db_schema, sbz_HTTPRequest request, String max_rows) {
    this(SubzeroJNI.new_sbz_TwoStageStatement(schema_name, path_prefix, role, sbz_DbSchema.getCPtr(db_schema), db_schema, sbz_HTTPRequest.getCPtr(request), request, max_rows), true);
  }

  public sbz_Statement mutateStatement() {
    long cPtr = SubzeroJNI.sbz_TwoStageStatement_mutateStatement(swigCPtr, this);
    return (cPtr == 0) ? null : new sbz_Statement(cPtr, false);
  }

  public sbz_Statement selectStatement() {
    long cPtr = SubzeroJNI.sbz_TwoStageStatement_selectStatement(swigCPtr, this);
    return (cPtr == 0) ? null : new sbz_Statement(cPtr, false);
  }

  public int setIds(String[] ids, int ids_count) {
    return SubzeroJNI.sbz_TwoStageStatement_setIds(swigCPtr, this, ids, ids_count);
  }

}
