/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.subzero.swig;

public class sbz_HTTPRequest {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sbz_HTTPRequest(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sbz_HTTPRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(sbz_HTTPRequest obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SubzeroJNI.delete_sbz_HTTPRequest(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public sbz_HTTPRequest(String method, String uri, String body, String[] headers, int headers_count, String[] env, int env_count) {
    this(SubzeroJNI.new_sbz_HTTPRequest(method, uri, body, headers, headers_count, env, env_count), true);
  }

}
