/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.subzero.swig;

public class SubzeroJNI {
  public final static native long new_sbz_HTTPRequest(String jarg1, String jarg2, String jarg3, String[] jarg4, int jarg5, String[] jarg6, int jarg7);
  public final static native void delete_sbz_HTTPRequest(long jarg1);
  public final static native long new_sbz_DbSchema(String jarg1, String jarg2, String jarg3);
  public final static native boolean sbz_DbSchema_isDemo(long jarg1, sbz_DbSchema jarg1_);
  public final static native void delete_sbz_DbSchema(long jarg1);
  public final static native long new_sbz_Statement(String jarg1, String jarg2, String jarg3, long jarg4, sbz_DbSchema jarg4_, long jarg5, sbz_HTTPRequest jarg5_, String jarg6);
  public final static native long sbz_Statement_mainStatement(String jarg1, String jarg2, String jarg3, long jarg4, sbz_DbSchema jarg4_, long jarg5, sbz_HTTPRequest jarg5_, String jarg6);
  public final static native long sbz_Statement_envStatement(long jarg1, sbz_DbSchema jarg1_, long jarg2, sbz_HTTPRequest jarg2_);
  public final static native void delete_sbz_Statement(long jarg1);
  public final static native String sbz_Statement_getSql(long jarg1, sbz_Statement jarg1_);
  public final static native String[] sbz_Statement_getParams(long jarg1, sbz_Statement jarg1_);
  public final static native String[] sbz_Statement_getParamsTypes(long jarg1, sbz_Statement jarg1_);
  public final static native long new_sbz_TwoStageStatement(String jarg1, String jarg2, String jarg3, long jarg4, sbz_DbSchema jarg4_, long jarg5, sbz_HTTPRequest jarg5_, String jarg6);
  public final static native long sbz_TwoStageStatement_mutateStatement(long jarg1, sbz_TwoStageStatement jarg1_);
  public final static native long sbz_TwoStageStatement_selectStatement(long jarg1, sbz_TwoStageStatement jarg1_);
  public final static native int sbz_TwoStageStatement_setIds(long jarg1, sbz_TwoStageStatement jarg1_, String[] jarg2, int jarg3);
  public final static native void delete_sbz_TwoStageStatement(long jarg1);
  public final static native long sbz_http_request_new_with_clone(String jarg1, String jarg2, String jarg3, String[] jarg4, int jarg5, String[] jarg6, int jarg7);
  public final static native long sbz_http_request_new(String jarg1, String jarg2, String jarg3, String[] jarg4, int jarg5, String[] jarg6, int jarg7);
  public final static native void sbz_http_request_free(long jarg1, sbz_HTTPRequest jarg1_);
  public final static native long sbz_two_stage_statement_new(String jarg1, String jarg2, String jarg3, long jarg4, sbz_DbSchema jarg4_, long jarg5, sbz_HTTPRequest jarg5_, String jarg6);
  public final static native long sbz_two_stage_statement_mutate(long jarg1, sbz_TwoStageStatement jarg1_);
  public final static native long sbz_two_stage_statement_select(long jarg1, sbz_TwoStageStatement jarg1_);
  public final static native int sbz_two_stage_statement_set_ids(long jarg1, sbz_TwoStageStatement jarg1_, String[] jarg2, int jarg3);
  public final static native void sbz_two_stage_statement_free(long jarg1, sbz_TwoStageStatement jarg1_);
  public final static native long sbz_statement_main_new(String jarg1, String jarg2, String jarg3, long jarg4, sbz_DbSchema jarg4_, long jarg5, sbz_HTTPRequest jarg5_, String jarg6);
  public final static native long sbz_statement_env_new(long jarg1, sbz_DbSchema jarg1_, long jarg2, sbz_HTTPRequest jarg2_);
  public final static native String sbz_statement_sql(long jarg1, sbz_Statement jarg1_);
  public final static native String[] sbz_statement_params(long jarg1, sbz_Statement jarg1_);
  public final static native String[] sbz_statement_params_types(long jarg1, sbz_Statement jarg1_);
  public final static native int sbz_statement_params_count(long jarg1, sbz_Statement jarg1_);
  public final static native void sbz_statement_free(long jarg1, sbz_Statement jarg1_);
  public final static native void sbz_db_schema_free(long jarg1, sbz_DbSchema jarg1_);
  public final static native long sbz_db_schema_new(String jarg1, String jarg2, String jarg3);
  public final static native int sbz_db_schema_is_demo(long jarg1, sbz_DbSchema jarg1_);
  public final static native String sbz_introspection_query(String jarg1, String jarg2, String jarg3, String jarg4);
  public final static native void sbz_introspection_query_free(String jarg1);
  public final static native int sbz_last_error_message(String jarg1, int jarg2);
  public final static native void sbz_clear_last_error();
  public final static native int sbz_last_error_length();
  public final static native int sbz_last_error_http_status();
}
