# workflow to build and test the project
name: ci

on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash

env:
  RUST_BACKTRACE: 1
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"
  SCCACHE_CACHE_SIZE: 2G
  RUSTC_WRAPPER: sccache
  SCCACHE_DIR: ${{ github.workspace }}/.sccache
  # SCCACHE_BUCKET: subzero-sccache
  RUST_TOOLCHAIN: nightly
  NODE_VERSION: 18

  POSTGRES_USER: postgrest_test_authenticator
  POSTGRES_PASSWORD: pass
  POSTGRES_DB: app

  MYSQL_USER: mysql_test_authenticator
  MYSQL_PASSWORD: pass
  MYSQL_DATABASE: public
  MYSQL_ROOT_PASSWORD: pass

  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1

jobs:
  build-test:
    name: build-test
    runs-on: ubuntu-latest
    steps:
      - name: "Set environmental variables"
        run: |
          echo "POSTGRESQL_DB_URI=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost:5432/$POSTGRES_DB" >> $GITHUB_ENV
          echo "MYSQL_DB_URI=mysql://$MYSQL_USER:$MYSQL_PASSWORD@localhost:3306/$MYSQL_DATABASE" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        if: ${{ !env.ACT }}

      - uses: ./.github/actions/rustup
        with:
          version: ${{ env.RUST_TOOLCHAIN }}
      - uses: ./.github/actions/cargo-cache
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}


      - run: cargo fmt --all -- --check

      - name: Install Dependencies
        run: |
          sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com
          sudo apt-get update
          sudo apt-get install --yes sqlite3

      - run: cargo build --workspace --exclude subzero-wasm

      - name: Build subzero-wasm 
        working-directory: subzero-wasm
        # run: wasm-pack build --release --target web
        run: |
          cargo build --package subzero-wasm --target=wasm32-unknown-unknown --release
          wasm-bindgen --out-dir=pkg-web --target=web --omit-default-module-path ../target/wasm32-unknown-unknown/release/subzero_wasm.wasm
          wasm-bindgen --out-dir=pkg-node --target=nodejs --omit-default-module-path ../target/wasm32-unknown-unknown/release/subzero_wasm.wasm


      - run: npm ci
        working-directory: subzero-node
      - run: npm run lint
        working-directory: subzero-node

      - name: Bring up db services
        run: docker-compose --file .github/docker-compose.yml --env-file .github/.env up -d

      - run: cargo test sqlite
      - run: cargo test postgresql -- --test-threads=1
      - run: cargo test mysql -- --test-threads=1

      - run: npm test
        working-directory: subzero-node

      - run: sccache --show-stats

      - name: Bring down db services
        run: docker-compose --file .github/docker-compose.yml --env-file .github/.env down
