name: CI

on:
  # pull_request:
  #   branches:
  #     - master
  push:
    branches:
      - master

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/rust-install
        if: ${{ env.ACT }}
      - uses: ./.github/actions/rustup
        if: ${{ !env.ACT }}
      - uses: ./.github/actions/rustfmt
  
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/rust-install
        if: ${{ env.ACT }}
      - uses: ./.github/actions/rustup
        if: ${{ !env.ACT }}
      - uses: ./.github/actions/cargo-cache
      - run: cargo clippy --all-targets

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/rust-install
        if: ${{ env.ACT }}
      - uses: ./.github/actions/rustup
        if: ${{ !env.ACT }}
      - uses: ./.github/actions/cargo-cache
      - run: cargo test -- --test-threads=1

